### ISSUE TITLE
TikzPictures not always rendering correctly in IJulia

### ISSUE THREAD

**Issue by smostars** [sisl/TikzPictures.jl#14]
Using PGFPlots.jl on Ubuntu in IJulia.
Axes are not being rendered correctly in IJulia cells. The axis labels are not correctly formatted / mostly missing.
We verified that lualatex produces the correct plot, and running pdf2svg produces the correct image.

The package works on other machines. Any idea what could be locally affecting it?

**Comment by mykelk** [comment]
Could it be related to #13? Does it work in Chrome on your Ubuntu machine?

**Comment by smostars** [comment]
Yes, I'm using Firefox browser. Thank you!
