### ISSUE TITLE
Build script

### ISSUE THREAD

**Issue by zsunberg** [sisl/TikzPictures.jl#23]
Should this have a `dep/build.jl` script that gives warnings and tries to install lualatex if it is missing?

**Comment by zsunberg** [comment]
If someone wants to tackle this, here is a start: https://github.com/zsunberg/LaserTag.jl/blob/master/deps/build.jl

**Comment by mykelk** [comment]
Yeah, that looks good. Texlive if pretty huge, so I was thinking that an error would be sufficient, pointing the user to the install. It would be nice to have a texlive.jl package that takes care of all this for you.

**Comment by zsunberg** [comment]
shoot - this package is very difficult to use with Travis-ci right now because the texlive version available via aptitude in  the ubuntu version they use does not have standalone.cls... very frustrating. Am I missing an easy way to use this on Travis?

**Comment by mykelk** [comment]
This seems to work, no?
https://github.com/sisl/TikzPictures.jl/blob/master/.travis.yml

**Comment by mykelk** [comment]
I think the key is `sudo apt-get install texlive-latex-extra`

**Comment by zsunberg** [comment]
yes latex-extra is definitely required, but the reason it is working and
mine is not is because it's on trusty - didn't know you could force that.

**Comment by mykelk** [comment]
`dist: trusty`
