### ISSUE TITLE
precompile

### ISSUE THREAD

**Issue by tawheeler** [sisl/TikzPictures.jl#25]
Is there a reason why TikzPictures does not have precompile enabled?

**Comment by mykelk** [comment]
I don't think so. I think this should probably be fixed. It may have contributed to the issue mentioned here: https://github.com/sisl/PGFPlots.jl/pull/71

**Comment by tawheeler** [comment]
LaTeXStrings supports precompile and we can drop Compat since we are up to date with 0.6, right?

**Comment by mykelk** [comment]
Yep!

**Comment by tawheeler** [comment]
resolved
