### ISSUE TITLE
update to Julia 0.4?

### ISSUE THREAD

**Issue by joachimdahl** [sisl/TikzPictures.jl#5]
In the latest git version of Julia 0.4 one gets the warning

julia> using TikzPictures
WARNING: uint64(x::FloatingPoint) is deprecated, use round(Uint64,x) instead.
 in depwarn at ./deprecated.jl:62
 in uint64 at deprecated.jl:49
 in include at ./boot.jl:253
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
while loading /home/joachim/.julia/v0.4/TikzPictures/src/TikzPictures.jl, in expression starting on line 206

which polutes notebooks using TikzPictures.

**Comment by mykelk** [comment]
Now fixed with v0.2.2.
