### ISSUE TITLE
Error with IJulia display of TikzPictures

### ISSUE THREAD

**Issue by MurrayT** [sisl/TikzPictures.jl#6]
I try to use TikzPictures in my IJulia session. Julia v0.3.11 and the following command fails

    using TikzPictures
    tp = TikzPicture("\\draw (0,0) -- (10,10);\n\\draw (10,0) -- (0,10);\n\\node at (5,5) {tikz \$\\sqrt{\\pi}\$};", options="scale=0.25", preamble="")

This gives the following response:

    opening file tikzpicture.svg: No such file or directory

     in systemerror at /usr/local/Cellar/julia/0.3.11/lib/julia/sys.dylib
     in open at /usr/local/Cellar/julia/0.3.11/lib/julia/sys.dylib (repeats 2 times)
     in writemime at /Users/murraytannock/.julia/v0.3/TikzPictures/src/TikzPictures.jl:216
     in sprint at iostream.jl:229
     in display_dict at /Users/murraytannock/.julia/v0.3/IJulia/src/execute_request.jl:28

It does not display the image. This is true for any Tikz I try to use. Should I report this at IJulia as well?

**Comment by mykelk** [comment]
I think there is an issue with your latex installation, rather than IJulia. Are you sure you can run lualatex? Try running the following, and it should give some insight into the issue:
```julia
using TikzPictures
tikzDeleteIntermediate(false)
tp = TikzPicture("\\draw (0,0) -- (10,10);\n\\draw (10,0) -- (0,10);\n\\node at (5,5) {tikz \$\\sqrt{\\pi}\$};", options="scale=0.25", preamble="")
run(`lualatex tikzpicture.tex`)
```

**Comment by MurrayT** [comment]
It appears to be an issue with my `pdf2svg` install I fixed by uninstalling and reinstalling `pdf2svg`
