### ISSUE TITLE
Support for other tex engines

### ISSUE THREAD

**Issue by mbaz** [sisl/TikzPictures.jl#7]
Would it be difficult to add support for other engines, such as pdflatex or xelatex? I'm thinking that maybe what engine to use could be configured by the user.

**Comment by mykelk** [comment]
I think we use lualatex so that it is easy to support the lua-specific things in the most recent release of Tikz. Why would one prefer to use pdflatex or xelatex instead?

**Comment by mbaz** [comment]
(I was unaware of the new graph layout algorithms in Tikz -- very nice).

I prefer to use xelatex because I've been using it for years and I have a
workflow that works. I don't even have luatex installed. My thinking is, if
{pdf,xe}latex support can be added easily to tikzpictures, it'd be a useful
feature to users like me. But adding support may be harder than I think;
for instance, maybe error reporting handling is very different between the
engines.

**Comment by mykelk** [comment]
This feature is now implemented in 06e12bc3ed4be42da92763c819a56bcdda8c31c8. You can use tikzCommand("xelatex") or whatever other command you want to use instead of lualatex.

**Comment by mbaz** [comment]
Thanks!
